### ISSUE TITLE
Случаются таймауты

### ISSUE THREAD

**Issue by purpleraven** [crazy-tea-party/grouple-recsys-production#22]
таймаут случается во врема ответа от сервиса. Не всегда, но бывает
у меня таймаут 6 секунд. Могу увеличить если сильно надо

```
04/05 08:53:55.384 ERROR recommend.RecomJmsService - Add user like REST error 30593 ElementId1{siteId=1, externalId=8035, typeName='null', topicId=1372
77, linkName='sindziuku_doktor_h_detektiv'}
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:5001/internal/rateItem": Read timed out; nested
 exception is java.net.SocketTimeoutException: Read timed out
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:742)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:668)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:412)
        at sun.reflect.GeneratedMethodAccessor418.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:188)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:143)
        at recommend.RecomJmsService$_pushItemRate_closure7.doCall(RecomJmsService.groovy:146)
        at recommend.RecomJmsService$_pushItemRate_closure7.doCall(RecomJmsService.groovy)
        at sun.reflect.GeneratedMethodAccessor415.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:399)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
```

**Comment by purpleraven** [comment]
less /opt/recommend/log/errors.log

**Comment by Kolyada** [comment]
Нужен доступ на папку /opt/recommend/log
6 секунд это очень долго, тем более с отложенной очередью,

**Comment by Kolyada** [comment]
Полностью вынес rateItem в очередь.

**Comment by Kolyada** [comment]
Таймауты с rateItem прекратились
