### ISSUE TITLE
Рекомендации похожих для юзера иногда падают

### ISSUE THREAD

**Issue by drayvs** [crazy-tea-party/grouple-recsys-production#8]
случается периодически 500 ошибка

**Comment by purpleraven** [comment]
сначала нужно нормально логи писать, тогда будет легко поправить

**Comment by purpleraven** [comment]
возможно нужный лог

```
2022-04-02 20:48:16.374 | INFO     | http_utils.recs.personal_similar_items_handler:get:23 - similarItems item_id=354 n_recs=6
ERROR:tornado.application:Uncaught exception GET /personalSimilarItems?item_id=354&user_id=876676&n_recs=6 (172.17.0.1)
HTTPServerRequest(protocol='http', host='recom.grouple.co', method='GET', uri='/personalSimilarItems?item_id=354&user_id=876676&n_recs=6', version='HTTP/1.0', remote_ip='172.17.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/webargs/core.py", line 445, in wrapper
    return func(*args, **kwargs)
  File "/app/http_utils/recs/personal_similar_items_handler.py", line 35, in get
    recs = model.similar_items_for_user(iix, uix, n_recs, return_scores=True)
  File "/app/models/implicitALS/model.py", line 117, in similar_items_for_user
    recs = self.model.recommend(item, k)
  File "implicit/recommender_base.pyx", line 175, in implicit.recommender_base.MatrixFactorizationBase.recommend
TypeError: 'int' object is not subscriptable

```

**Comment by Kolyada** [comment]
В ходе работ появление данной ошибки удалось исключить или значительно снизить частоту появления.
